server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(wasm)$ {
        default_type application/wasm;
    }

    gzip on;
    gzip_types
        application/wasm
        application/javascript
        text/css
        application/json
        text/plain
        image/svg+xml;
}